version: '2'
services:
  mariadb:
    image: mariadb:10.9
    environment:
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
  wordpress:
    image: wordpress
    volumes:
      - './:/var/www/html/wp-content/plugins/gatewayapi'
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
